client/aci/analytics.go
client/aci/client.go
client/aci/client_test.go
client/aci/exec.go
client/aci/get.go
client/aci/rp.go
client/aci/rp_test.go
client/aci/types.go

ACI GPU Support Changes in Client

---

aci.go
aci_test.go

Carries virtual-kubelet/virtual-kubelet#639

[Carry] Memory limits rounding to 0.1G added.

---

cmd/virtual-kubelet/main.go
cmd/virtual-kubelet/ocagent.go
go.mod

Adds support for using ocagent to export tracing data.

Add tracing flags to CLI.

---

README.md

add warning about SP expiration within a year for manual VK installation 
add warning about az aks install-connector being deprecated

SP warning / az aks install-connector deprecation

---

README.md

This README had some outdated directions for installing Helm, and also had some Helm v2 syntax. I have pointed to the official Helm install info and updated the syntax to Helm v3. 
Signed-off-by: Bridget Kromhout <bridget@kromhout.org>

Updates for Helm 3

---

README.md

Given the removal of the aci-connector command: https://github.com/Azure/azure-cli/pull/15084

Removing reference to aci-connector

---

cmd/virtual-kubelet/main.go

update k8sVersion var to match k8s.io/kubernetes v1.18.4 import update from https://github.com/virtual-kubelet/azure-aci/pull/52

update k8sVersion var to match k8s.io/kubernetes v1.18.4 import

---

README.md

Made 2 changes to readme.md
1. Network contributor name changed to the correct name.
2. Nodename added to helm install.

Role name and node name in readme.md 

---

README.md

Fixes https://github.com/virtual-kubelet/azure-aci/issues/93

Add guides for Windows virtual node installation

---

provider/aci.go

Add chinaeast2 as supported region

---

Makefile
e2e/fixtures/nginx.yml
e2e/fixtures_test.go
e2e/pods_test.go
hack/e2e/aks.sh

The build pipeline runs these tests so, back porting to this release branch.

[1.4] Backport e2e tests

---

client/api/api.go
client/api/api_test.go
client/api/utils.go
go.mod

Add unit tests to 100% coverage and minor var renaming.
https://github.com/virtual-kubelet/azure-aci/issues/186

Unit test for client/api/api.go at 100% coverage

---

.circleci/config.yml
Makefile

Try to add code coverage in the CI

Test adding code coverage

---

go.mod
provider/aci.go
provider/aci_test.go

This PR will add the support of the AzureFile CSI driver in addition to the unit test.
Fixes #88

feat: Add support for CSI driver

---

.gitignore
Makefile
provider/aci.go
provider/aci_test.go

Update the Azure file CSI driver inline volume support: https://docs.microsoft.com/en-us/azure/aks/azure-files-volume#mount-file-share-as-an-inline-volume

bug: fix CSI driver inline implementation

---

helm/README.md

Add helm chart documentation

---

.github/workflows/chart.yml

ci: Add helm chart github action

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/new_issue.md
.github/workflows/create-release.yml

ci: Add release workflow and issue/feature template

---

.github/workflows/e2e-tests.yml

Make sure to add random number in case the pr_sha is empty

ci: Enhance random name for cluster name and resource group

---

docs/DOWNGRADE-README.md

This change updates the doc based on the latest experiment.

doc: Revise the downgrade readme

---

.github/workflows/tests.yml

The removed condition will fix the master pipeline scenario from failing.

Remove pull_request check in checkout step

---

docs/DOWNGRADE-README.md

Revision based on live debugging.  There are TBD items that will be added later.

Revise the downgrade README.md

---

charts/virtual-kubelet/Chart.yaml
charts/virtual-kubelet/README.md
charts/virtual-kubelet/values.yaml

Bump the helm chart to the new version.

chore: Bump helm chart version

---

pkg/provider/config.go
pkg/provider/config_test.go

Copy the same files to the new pkg folder:
- https://github.com/virtual-kubelet/azure-aci/blob/ff32cfddce/provider/config.go
- https://github.com/virtual-kubelet/azure-aci/blob/ff32cfddce/provider/config_test.go

chore: Move config to new folder

---

.github/workflows/codeql.yml
CODEOWNERS
OWNERS

- Add CodeQL 
- Fix CODEOWNERS file

ci: Add CodeQL workflow

---

CODETRIBUTING.md
CODE_OF_CONDUCT.md

- Add Contributing guidance.
- Add Code of Conduct doc.
Fixes #194

doc: Add Contributing and CoC doc

---

pkg/provider/aci.go
pkg/provider/aci_test.go
pkg/provider/aci_volumes_test.go

The old code can be found [here](https://github.com/virtual-kubelet/azure-aci/tree/master/provider).

chore: Update azure aci provider to use SDK

---

.github/workflows/e2e-tests.yml
.github/workflows/tests.yml
Dockerfile
Makefile

- Enhance Dockerfile to have to go mod cached
- Update image tag in makefile

ci: Enhance CI and Dockerfile

---

.github/PR_TEMPLATE.md
.github/markdown-links-config.json
.github/pr-title-config.json
.github/workflows/create-release.yml
.github/workflows/markdown-link-check.yml
.github/workflows/pr-title-lint.yml
README.md

Add more workflows to enhance the quality of the repo:
- image scan
- pr title check 
- markdown link check
Also, Add PR template

ci: Add image scan, pr title and markdown link checks workflows

---

.github/workflows/create-release.yml
goreleaser.yml

release workflow passed on my fork
https://github.com/helayoty/azure-aci/actions/runs/3270114816/jobs/5378370789

ci: Fix amd goarm issue

---

charts/virtual-kubelet/Chart.yaml
charts/virtual-kubelet/README.md
charts/virtual-kubelet/values.yaml
docs/DOWNGRADE-README.md

- update helm chart
- update downgrade doc

chore: Bump helm chart for v1.4.6

---

client/aci/client_test.go
e2e/pods_test.go
e2e/volume_test.go
go.mod
go.sum
pkg/metrics/metrics.go
pkg/provider/aci.go
pkg/provider/aci_network.go
pkg/provider/aci_test.go
pkg/provider/aci_utils.go
pkg/provider/aci_utils_test.go
pkg/provider/aci_volumes_test.go
pkg/provider/containergroup_to_pod.go
pkg/provider/containergroup_to_pod_test.go
pkg/provider/podsTracker.go
pkg/tests/utils.go

fix: Fix pod status migration

---

.github/ISSUE_TEMPLATE/new_issue.md
.github/PR_TEMPLATE/new_pr.md
.github/workflows/chart.yml
.github/workflows/e2e-tests.yml
.github/workflows/lint.yml
.github/workflows/markdown-link-check.yml
.github/workflows/tests.yml
docs/UPGRADE-README.md

- Add an upgrade release document
- Update pipelines to skip docs

docs: Add upgrade document

---

.github/workflows/lint.yml
Makefile
client/api/api_test.go
e2e/initcontainer_test.go
e2e/pods_test.go
pkg/provider/aci_init_container_test.go
pkg/provider/aci_volumes_test.go

Add go fmt check to Makefile and to the pipeline

ci: Add go fmt check

---

.github/workflows/chart.yml

Signed-off-by: Heba Elayoty <31887807+helayoty@users.noreply.github.com>

ci: Update chart.yml

---

.github/pr-title-config.json
.github/workflows/chart.yml
.github/workflows/create-release-pull-request.yml
.github/workflows/create-release.yml
.github/workflows/e2e-tests.yml
.github/workflows/lint.yml
.github/workflows/tests.yml
Makefile
README.md
charts/virtual-kubelet/README.md
docs/DOWNGRADE-README.md
docs/UPGRADE-README.md
hack/e2e/aks.sh

Introduce a pull request creation pipeline to kick off the release. 
- Update all helm/files with the new release tag
- Once the PR got merged, release and publish helm chart pipelines will start 

ci: Update release and publish chart pipelines

---

.github/workflows/create-release-pull-request.yml

Signed-off-by: Heba Elayoty <31887807+helayoty@users.noreply.github.com>

ci: Update create-release-pull-request.yml

---

.github/workflows/chart.yml

Signed-off-by: Heba Elayoty <31887807+helayoty@users.noreply.github.com>

ci: Update helm chart pipeline

---

pkg/client/client_apis.go
pkg/provider/aci.go
pkg/provider/containergroup_to_pod.go

chore: Remove redundant logs

---

.github/workflows/aks-addon-tests.yml
.github/workflows/create-release-pull-request.yml
.github/workflows/create-release.yml
.github/workflows/e2e-tests.yml
.github/workflows/lint.yml
.github/workflows/tests.yml
docker/init-container/Dockerfile
docker/virtual-kubelet/Dockerfile
go.mod
pkg/provider/aci_test.go

chore: Upgrade go to 1.19

---

.github/workflows/e2e-tests.yml
.github/workflows/tests.yml
Makefile
hack/ci/create_aks_credentials.sh
hack/ci/create_credentials.sh
hack/ci/create_loganalytics_auth.sh

- Update unit tests Makefile target to generate nessecarry test auth files.
- Remove unused env variables from the unit test pipeline

test: Update unit test target for local development

---

Makefile
README.md

Update the main README file with the correct steps to install the helm chart.
Fixes #376

docs: Update Readme file

---

pkg/provider/aci_test.go
pkg/provider/aci_volumes_test.go
pkg/provider/podsTracker_test.go

added unit test for getImagePullSecrets in aci.go with dockercfg secret. Also applied formatting to aci_test.go and podsTracker_test.go

test: added unit test for getImagePullSecrets with dockercfg secret

---

pkg/provider/aci_test.go

added unit test for getImagePullSecrets in aci.go with dockerc config JSON secret.

test: added unit test for getImagePullSecrets with docker config JSON

---

pkg/provider/aci.go
pkg/provider/aci_test.go

added unit test for getGPUSKU in aci.go. Fixed error message to use the right values.

test: added unit test for getGPUSKU

---

pkg/metrics/real_time_test.go

Issue Link: https://github.com/virtual-kubelet/azure-aci/issues/514

test: Added unit test for filterOutContainerNotInPod

---

cmd/init-container/main.go
e2e/initvalidation_test.go

Verify init-validation container code is executed by verifying the success log message is received

test: adding test for init validation

---

Makefile
charts/virtual-kubelet/Chart.yaml
charts/virtual-kubelet/README.md
charts/virtual-kubelet/values.yaml
docs/UPGRADE-README.md

Reverting because previous release didn't get triggered

fix: revert release version

---

.github/workflows/create-release.yml
Makefile

Add back the master branch to the pull_request action for the release pipeline.

ci: Add master branch to release pipeline

---

Makefile
goreleaser.yml

- Update goreleaser version to 2
- UpdateQemu version to 7.2.0-1
- Replace multiarch/qemu-user-static with mcr.microsoft.com/mirror/docker/multiarch/qemu-user-static:7.2.0-1

fix: update goreleaser

---

.github/workflows/publish-image.yml
.github/workflows/publish-init-container-image.yml
Makefile

The inputs call for `workload_call` should be `${{ inputs.<variable_name> }}`, not payload.

fix: Update registry and release version inputs

---

hack/e2e/aks-addon.sh
hack/e2e/aks.sh
hack/e2e/aks_2.sh

Create Network security group and Network security group rules for the vnet/subnet used in the e2e tests.

test: Create nsg for the e2e tests
