virtual-kubelet/azure-aci

- aci.go
- config.go
* Allows for more declaritive tools to deploy a non AKS managed ACI integration
* Falls back to traditional `vk-sha()` name if not set
Closes: #7
Signed-off-by: Graham Hayes <gr@ham.ie>
> Allow deployer to set networkProfile name

- aci.go
Carries virtual-kubelet/virtual-kubelet#640
> [Carry] Bugfix: Azure ACI provider skips ConfigMap Data exctraction on volumes mapping

- aci.go
As ACI currently combined args + command, a pod
with args and no command will have un-expected behaviour.
This blocks the un-expected behavior.
Related: #10
Signed-off-by: Graham Hayes <gr@ham.ie>
> Do not accept args without command

- aci.go
- client/client.go
- cmd/virtual-kubelet/main.go
Avoiding the ARM throttling issues. when same connection to same ARM instance is reused.
> Set transport to not reuse conns

- client/aci/client_test.go
I had the subscription and SP used for CI testing changed. this change updates the networkprofile used for testing the vnet CG creation.
> Update used network profile for testing

- client/aci/client_test.go
- client/auth.go
- client/client.go
- client/network/client.go
- provider/aci.go
This is a requirement as AKS clusters will not share the SP anymore, and instead a separate user identity per-addon/system deployment will be used.
> Support to authenticate through user identity

- cmd/virtual-kubelet/main.go
- provider/aci.go
- provider/aci_test.go
This allows `--cluster-domain` to be passed to virtual kubelet like a
traditional kublet, and use this to generate search-domains for
`/etc/resolv.conf`
* Only apply to pods with `DNSClusterFirst` to match kubelet
* Merge search-domains with any set in the `dnsConfig`
* Set `ndots` to the default 5
Related: #641
Depends-On: virtual-kubelet/virtual-kubelet#642
Signed-off-by: Graham Hayes <gr@ham.ie>
> Allow virtual-kubelet to use cluster domain

- Dockerfile
- README.md
- go.mod
- go.sum
- helm/templates/deployment.yaml
- helm/templates/secrets.yaml
- helm/values.yaml
- provider/aci.go
Make changes for:
1. update document for Helm 3. See issue #57 and #56 
2. update the Kubernete deployment  version from extensions/v1beta1 to apps/v1, since extensions/v1beta1 has been not supported from Kubernete 1.6. see issue #44 
3. update the code to support install ACI Virtual Kubelet in Non-AKS cluster, and update corresponding documents.
> update for Helm 3 and Kubernete 1.6

- azure-pipelines.yml
We're disabling this trigger, as the pipeline is failing, but also not required.
> Disable trigger on Azure-pipeline

- provider/aci.go
"alpha.service-controller.kubernetes.io/exclude-balancer" has been removed since v1.19.0, we should ensure the new label "node.kubernetes.io/exclude-from-external-load-balancers" is added for virtual node:
```
// labelNodeRoleExcludeBalancer specifies that the node should not be considered as a target
// for external load-balancers which use nodes as a second hop (e.g. many cloud LBs which only
// understand nodes). For services that use externalTrafficPolicy=Local, this may mean that
// any backends on excluded nodes are not reachable by those external load-balancers.
// Implementations of this exclusion may vary based on provider. This label is honored starting
// in 1.16 when the ServiceNodeExclusion gate is on.
labelNodeRoleExcludeBalancer = …
```
> Ensure label node.kubernetes.io/exclude-from-external-load-balancers is added to virtual node

- go.mod
- go.sum
This adds on-by-default TLS client authentication.
If client certs are not specified then the API server will not be setup.
Full diff: https://github.com/virtual-kubelet/node-cli/compare/v0.3.1..v0.4.0
Release notes: https://github.com/virtual-kubelet/node-cli/releases/tag/v0.4.0
Before releasing with this change, we'll need to work out how to deal with certificates.
> Bump node-cli to 0.4.0

- client/aci/logs.go
> Don't add tail to uri query to if it is not set for `kubectl logs`

- provider/aci.go
> Fix the issue that cmd arguments are discarded by kubectl exec

- provider/aci.go
- provider/aci_test.go
Virtual node should not be added to LoadBalancer backend address pool and route tables should not be updated for it either. Hence, this PR marks virtual node as unmanaged.
Refer cloud provider docs https://kubernetes-sigs.github.io/cloud-provider-azure/topics/cross-resource-group-nodes/#unmanaged-nodes.
Fix #89.
> Add kubernetes.azure.com/managed=false label for virtual node

- .circleci/config.yml
- Dockerfile
- go.mod
- go.sum
- update github.com/gorilla/websocket to v1.4.1
- update go version to 1.16
> chore: update github.com/gorilla/websocket to v1.4.1

- .github/workflows/e2e-tests.yml
Azure login action will not work with `pull_request` but only `pull_request_target` which has security issues and I didn't want to use it with e2e-tests. moving the pipeline to only work with push to master.
> feat: Remove e2e-test pipeline pull_request

- e2e/fixtures/csi-driver.yml
- e2e/fixtures/namespace.yml
- e2e/fixtures_test.go
- e2e/pods_test.go
- hack/e2e/aks.sh
In this PR:
- Update `aks.sh` script to create a storage account according to the [documentation](https://docs.microsoft.com/en-us/azure/aks/azure-files-volume#create-an-azure-file-share)
- Add test case for CSI driver 
- Remove `bytes` import as there is no need to read the file.
//@andyzhangx
> test: e2e tests for CSI driver

- .github/workflows/e2e-tests.yml
- .github/workflows/tests.yml
- Makefile
- Move subscription, clientID, and tenantID to be environment secrets.
- Increase e2e test timeout
> fix: Move env to environment secrets & increase test timeout

- .github/workflows/e2e-tests.yml
In order to be able to delete the image after running the e2e tests, we needed to remove the `v` from the tag.
> fix: Remove 'v' from image tag

- .github/workflows/chart.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/publish-images.yml
- .github/workflows/tests.yml
- Makefile
- hack/e2e/aks.sh
In this PR:
- Move e2e images to be in ACR instead of GH packages. (Fixes #282   #283 )
- Fix checkout action to be for the current 
-  Create a separate workflow to publish a new image with the new releases.
- Increase `SemVer` to include (v*.*.*.*)
> ci: Move e2e images to be in a temp ACR instead of GH packages

- .github/workflows/e2e-tests.yml
In the case of running e2e-test workflow for master, the pr_sha will be empty. the [aks name](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftcontainerservice) can't end with `-`.
> ci: Remove dash from cluster name

- .github/workflows/e2e-tests.yml
- .github/workflows/tests.yml
- Upgrade `tests` and `e2e-tests` workflow to use go `1.18`
- Remove duplicate `checkout` step in tests workflow
> chore: Upgrade workflows to go 1.18

- pkg/analytics/analytics.go
- pkg/analytics/analytics_test.go
Migrate from the custom SDK to the official Azure container instance SDK
old files:
- https://github.com/virtual-kubelet/azure-aci/blob/master/client/aci/analytics.go
- https://github.com/virtual-kubelet/azure-aci/blob/master/client/aci/analytics_test.go
> chore: Migrate ACI log analytics to use Azure SDK

- client/aci/client_test.go
- pkg/client/client.go
- pkg/client/client_apis.go
- pkg/client/extensions.go
- pkg/client/interfaces.go
- pkg/client/retry.go
- pkg/types.go
Migrate to use containersClient, ContainerGroupClient, and LocationClient instead of the custom clients.
Old code:
- https://github.com/virtual-kubelet/azure-aci/blob/master/client
- https://github.com/virtual-kubelet/azure-aci/blob/master/client/client.go
- https://github.com/virtual-kubelet/azure-aci/blob/master/client/environments.go
- https://github.com/virtual-kubelet/azure-aci/blob/master/provider/aci.go#L261-L299
- https://github.com/virtual-kubelet/azure-aci/blob/master/provider/aci.go#L522-L650
> chore: Migrate to use Azure SDK clients

- Makefile
Now if any go files (minus e2e tests and test files) are modified, make
will rebuild.
Before this change you have to call `make clean build` to do a rebuild.
> chore: Use correct make deps for bin/% target

- pkg/client/client.go
- pkg/provider/aci.go
- pkg/provider/aci_test.go
- pkg/provider/aci_volumes_test.go
Add an explicit name for the CG properties wrapper to fix `MarshalJson` issue
> fix: Add explicit name for the CG properties wrapper to fix json issue

- .github/workflows/tests.yml
- Makefile
- charts/virtual-kubelet/templates/deployment.yaml
- charts/virtual-kubelet/values.yaml
- cmd/virtual-kubelet/main.go
- go.mod
- go.sum
- pkg/client/client_apis.go
- pkg/client/metrics_client.go
- pkg/provider/aci.go
- pkg/provider/aci_test.go
- Implement a switch option between the VK v1 (using custom client) and v2 (SDK migration).
- Add new env variable `USE_VK_VERSION_2` in the helm chart. true -> V2 & false -> V1
- Comment the `Location` API from V2 until got fixed. 
- Skip the following UT until the `Location` API got fixed:
- **TestCreatePodWithGPU**
- **TestCreatePodWithGPUSKU**
The old code ->  https://github.com/virtual-kubelet/azure-aci/tree/master/cmd/virtual-kubelet/main.go
> chore: Switch main.go to use V2(SDK migration)

- charts/virtual-kubelet/values.yaml
- pkg/provider/aci.go
- pkg/provider/aci_network.go
- Pass default kube_DNS via helm instead of static value in the code.
- Update `formDNSSearchFitsLimits` to match k8s kubelet.
- Pass `ctx` instead of `context.TODO`.
- Remove azureIP to have only one IP in the `resolv.conf`.
> fix: Remove all but the coreDNS ip from resolv.conf

- charts/virtual-kubelet/README.md
- charts/virtual-kubelet/templates/clusterrolebinding.yaml
- charts/virtual-kubelet/templates/deployment.yaml
- charts/virtual-kubelet/templates/namespace.yml
- charts/virtual-kubelet/templates/secrets.yaml
- charts/virtual-kubelet/templates/serviceaccount.yaml
- charts/virtual-kubelet/values.yaml
- client/aci/client_test.go
- deploy/deployment.yaml
- hack/e2e/aks-addon.sh
- hack/e2e/aks.sh
- pkg/auth/auth.go
- pkg/provider/aci.go
- pkg/provider/aci_network.go
- pkg/provider/aci_test.go
- Add namespace to the helm chart
- Check to get ACI `resourcegroup`, `region`, and `vnet` name from azure.json in case env variables are not set.
- Add deployment file for aks addon e2e
> ci: Cleanup e2e scenarios 

- e2e/fixtures/win-pod.yml
- e2e/pods_test.go
- e2e/pods_win_test.go
- hack/e2e/aks-addon.sh
- hack/e2e/aks.sh
- pkg/network/aci_network.go
- pkg/provider/aci.go
- pkg/provider/containergroup_to_pod.go
- pkg/validation/validator.go
> fix: Skip IPAddress check for windows containers

- hack/e2e/aks-addon.sh
- hack/e2e/aks.sh
Fix the k8s version until `virtual-kubelet` fixes the migration issue > 1.24
> chore: Fixate the k8s version to > 1.24

- go.mod
- go.sum
- pkg/network/aci_network.go
- pkg/provider/aci.go
We mostly follow this guide for code migration:
https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md
> refactor: Migrate network pkg to Azure SDK v2 - Part 3

- .github/workflows/e2e-tests.yml
- charts/virtual-kubelet/templates/deployment.yaml
- charts/virtual-kubelet/values.yaml
- hack/e2e/aks-addon.sh
- hack/e2e/aks.sh
- Fix init-container env variables in the helm chart
- Update init container names in the e2e scripts 
- Run helm e2e pipeline with the releases
> ci: Update helm chart and e2e

- Makefile
- hack/e2e/aks-addon.sh
- hack/e2e/aks.sh
Update `k8s-version` to be configurable for both `aks.sh` and `aks-addon.sh`
The default value is `1.23.12`
> test: Pass k8s version as variable to e2e scripts

- cmd/init-container/main.go
- pkg/provider/aci.go
- pkg/provider/aci_volumes.go
- pkg/validation/validator.go
> fix: Remove extra info logs for the success scenarios

- .github/workflows/aks-addon-tests.yml
- Makefile
- docker/virtual-kubelet/Dockerfile
- Remove pull_request types from aks-e2e pipeline
- Increase e2e timeout
- Pass image version and timestamp to the dockerfile
> fix: Fix image build version

- e2e/fixtures/csi-driver.yml
- e2e/fixtures/hpa.yml
- e2e/fixtures/multi-volume.yml
Kubernetes is migrating its image registry from [k8s.gcr.io](http://k8s.gcr.io/) to [registry.k8s.io](http://registry.k8s.io/).
Part of kubernetes/k8s.io#4780.
> fix: migrate from k8s.gcr.io to registry.k8s.io

- pkg/provider/vk_node.go
> spec.template.spec.nodeSelector[beta.kubernetes.io/os]: deprecated since v1.14; use "kubernetes.io/os" instead
To maintain compatibility, the virtual node should declare both styles of OS information, so that the Pod being scheduled to the virtual node can choose any of the following options
* use the legacy style `beta.kubernetes.io/os` nodeSelector
* migrate to use the new `kubernetes.io/os` nodeSelector before the `beta` one is dropped completely from API server
Currently, we only report `beta.kubernetes.io/os`, which will block the users from working on the nodeSelector migration.
> feat: report both old and new styles of node OS information

- README.md
- docs/windows-virtual-node.md
The changes add the instructions for manually installing a virtual node to run windows ACI instances.
> docs: Add instructions to install windows virtual node

- pkg/provider/aci_test.go
- pkg/tests/utils.go
Added unit test for deleteContaierGroup in aci.go. This will also test updatePodStatus method in podsTracker.go by attaching a podTracker object to the test provider.
> test: added unit test for deleteContainerGroup

- pkg/provider/aci_test.go
added unit test for getPodStatus in aci.go with one positive and three negative test cases
> test: added unit test for getPodStatus

- pkg/provider/podsTracker_test.go
added unit test for processPodUpdates in podsTracker.go
> test: added unit test for processPodUpdates

- Makefile
Because the third-party extension (aka `codecov`) coverage can get delayed reporting back the code coverage, we wanted to display the full coverage report with the total with each run using go native way `go tool cover -func=coverage.out`.
> test: Display code coverage for each func/pkg and the total coverage

- pkg/provider/aci_test.go
- pkg/provider/podsTracker_test.go
- pkg/tests/utils.go
added unit test for cleanupDanglingPods in podsTracker.go
- test case: podLister returns an additional pod than what is reported by the client so the dangling pod is deleted so the two are in sync
> test: added unit test for cleanupDanglingPods

- pkg/provider/aci_test.go
Issue Link: https://github.com/virtual-kubelet/azure-aci/issues/504
+ Converted v1 to corev1 for import package per convention.
> test: Unit Test for GetContainerLogs

- pkg/provider/podsTracker_test.go
- pkg/tests/utils.go
added unit test for updatePodsLoop in podsTracker.go
> test: added unit test for updatePodsLoop

- pkg/analytics/analytics.go
- pkg/analytics/analytics_test.go
- pkg/auth/auth.go
- pkg/auth/auth_test.go
- pkg/client/client_apis.go
- pkg/client/extensions.go
- pkg/client/interfaces.go
- pkg/featureflag/feature_flag_test.go
- pkg/metrics/cache.go
- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
- pkg/metrics/real_time.go
- pkg/metrics/real_time_test.go
- pkg/network/aci_network.go
- pkg/network/mock_aci_network.go
- pkg/provider/aci_init_container_test.go
- pkg/provider/config.go
- pkg/provider/config_test.go
- pkg/provider/docker_config.go
- pkg/provider/docker_config_test.go
- pkg/provider/mock_aci_test.go
- pkg/provider/podsTracker.go
- pkg/provider/podsTracker_test.go
- pkg/validation/validator.go
To be able to write unit tests for the `aci_network` package, we need to mock the networking client along with create/get APIs.
In order to achieve that, we introduce a new interface, `ProviderNetworkInterface` that will implement:
- getSubnetClient
- getACISubnet
- getACISubnet
>> Note: A separate commit has been added for missing copyright headers in some files.
> test: Add network testing mocks

- pkg/network/aci_network_test.go
added unit test for shouldCreateSubnet in aci_network.go
> test: added unit test for shouldCreateSubnet

- hack/ci/create_aks_credentials.sh
- pkg/provider/aci_test.go
Remove skipping GPU unit tests, as ACI mocks were not implemented before.
> test: Remove skipping GPU unit tests

- pkg/network/aci_network_test.go
added unit test coverage for validateNetworkConfig in aci_network.go
Test case break down:
- Provider Vnet name is set but environment variable is not: tc2
- Provider Vnet name is not set but environment variable is: tc3
- Both provider Vnet name and environment variable is set: tc6
- Neither provider Vnet name nor environment variable is set: tc1
- Provider Vnet resource group is set but environment variable is not: tc2
- Provider Vnet resource group is not set but environment variable is: tc4
- Both provider Vnet resource group and environment variable is set: tc6
- Neither provider Vnet resource group nor environment variable is set: tc3
- Provider Subnet name is set but environment variable is not: tc2
- Provider Subnet name is not set but environment variable is
-- malformed: tc7 …
> test: added unit test for validateNetworkConfig

- pkg/provider/aci.go
- pkg/provider/aci_init_container_test.go
- pkg/provider/aci_test.go
- pkg/provider/containergroup_to_pod.go
- pkg/provider/containergroup_to_pod_test.go
started is always true. make pod with startup probe fail.
ensure terminated container group report a terminated state in k8s.
> fix: container state.

- Makefile
- hack/e2e/aks-addon.sh
- hack/e2e/aks.sh
Removed hardcoded AKS version 1.24.10 which is no longer supported
> test: changing aks version to default

- .github/dependabot.yml
- .github/workflows/aks-addon-tests.yml
- .github/workflows/chart.yml
- .github/workflows/create-release-pull-request.yml
- .github/workflows/create-release.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/markdown-link-check.yml
- .github/workflows/pr-title-lint.yml
- .github/workflows/tests.yml
Updating/adding permissions block for workflow file according to [breaking change doc](https://docs.opensource.microsoft.com/github/apps/permission-changes/)
- List of available scopes: https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#permissions
- Permission breakdown per scope: https://docs.github.com/en/enterprise-cloud@latest/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-pull-requests
> chore: updating permissions for workflow files

- e2e/fixtures/csi-driver.yml
- e2e/fixtures/hpa.yml
- e2e/fixtures/multi-volume.yml
E2E pipeline has been failing due to timeout. Impacted test cases: TestPodLifecycle, TestPodWithCSIDriver, TestPodWithMultiVolume
`Error: Failed to start container busybox, Error response: to create containerd task: failed to create shim task: failed to create container 13497419b8081cc7082dadd06ce7883bdb5d490b69e4ffbea77331f89ab95744: guest RPC failure: failed to create container: failed to run runc create/exec call for container 13497419b8081cc7082dadd06ce7883bdb5d490b69e4ffbea77331f89ab95744 with exit status 1: container_linux.go:380: starting container process caused: exec: "sh": executable file not found in $PATH: unknown`
Fix: specifying /bin/sh seems to do the trick
> fix: fix e2e failed cases

- e2e/fixtures/confidential_container_pod.yml
- e2e/fixtures/csi-driver.yml
- e2e/fixtures/hpa.yml
- e2e/fixtures/initcontainers_ordertest_pod.yml
- e2e/fixtures/multi-volume.yml
Changing e2e test pods image registry from docker to MCR as a part of docker rate limit changes.
> fix: update image registry to MCR

- pkg/network/aci_network.go
- pkg/network/aci_network_test.go
- Added a check for subnet properties.AddressPrefixes incase properties.AddressPrefix is not set and added necessary unit tests
- To differentiate between subnet create vs update scenario:
- changed the existing "createSubnet" boolean to "updateSubnet" to minimize confusion - this bool indicates that an update is needed
- introduced new boolean "createNewSubnet" which will only be set to true if we cannot retrieve the ACI subnet from GetACISubnet function
- Updated function "CreateACISubnet" to "CreateOrUpdateACISubnet" and distinguished create vs update scenario using the "createNewSubnet" boolean from above
- updated logic so addressPrefix/addressPrefixes is only set on create
> fix: separate subnet create vs update and check for addressPrefixes field

- .github/workflows/create-release.yml
- .github/workflows/publish-image.yml
- .github/workflows/publish-init-container-image.yml
- In `Publish the Azure Virtual Kubelet image` pipeline, the checkout action was missing
- Add the release version variable to `Publish the init validation image` pipeline to checkout the right tag.
> ci: Add the missing checkout action and pass the release version

- Makefile
- charts/virtual-kubelet/values.yaml
- hack/e2e/aks-addon.sh
- hack/e2e/aks.sh
- remove the 'v' in front of the tag
- update e2e scripts to use the right helm variable for init image tag: initImage.initTag
> fix: correct init image tag

- .github/workflows/create-release-pull-request.yml
Leaving out the 'v' when reading init image version so the correct value is populated for helm variable initImage.initTag in order for the init container to pull the correct image
> ci: update regex for init container version 

- .github/workflows/create-release.yml
- Makefile
remove 'v' from the regex so init-tag is properly populated
> ci: update init image tag regex for release pipeline
